// react/src/App.jsx
import './App.css'

import { Game } from './components/Game.jsx'
import { GameFooter } from './components/GameFooter'
import { useGame } from './hooks/useGame.jsx'

function App () {
  const { doMove, gameState, newGame } = useGame({ random: true })

  return (
    <>
      <h1>Ta - Te - Ti</h1>
      <section className='container'>
        <Game
          gameState={gameState}
          doMove={doMove}
        />

        <GameFooter
          gameState={gameState}
          newGame={newGame}
        />
      </section>
    </>
  )
}

export default App

// vue/src/App.vue
<script setup lang="ts">
import GameBoard from './components/GameBoard.vue';
import GameFooter from './components/GameFooter.vue';
import { useGame } from './hooks/useGame';

const {doMove, newGame, gameState} = useGame({random:true})
</script>

<template>
  <h1>Tic-tac-toe</h1>
  <div class="container">
    <GameBoard
      :doMove="doMove"
      :gameState="gameState"    
    />
    <GameFooter
      :gameState="gameState"
      :newGame="newGame"
    />
  </div>

</template>
