// vue/src/components/GameFooter.vue
<template>
  <div class="turns">
    <SquareGame :isSelected="gameState.turn === 'x'">{{ gameState.customIcons.x }}</SquareGame>
    <SquareGame>{{ gameState.customIcons.o }}</SquareGame>
  </div>
  <div class="new-game-container">
    <HoldButton
      :handleClick="handleNewGame"
      :time="300"
    >
      Nuevo juego
    </HoldButton>
    <label>
      Nuevos íconos
      <input
        v-model="newIconsCheck"
        type="checkbox"
      />
    </label>
  </div>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import SquareGame from './SquareGame.vue'
import HoldButton from './holdButton.vue'

const props = defineProps(['gameState', 'newGame'])

const newIconsCheck = ref(true)

const handleNewGame = () => {
  props.newGame({ redefineIcons: newIconsCheck.value })
}
</script>

// react/src/components/GameFooter.jsx
import { HoldButton } from './holdButton'
import '../App.css'
import { Square } from './Square'
import { useState } from 'react'

export function GameFooter ({ gameState, newGame }) {
  const customIcons = gameState.customIcons
  const [keepIcons, setKeepIcons] = useState(false)

  const handleNewGame = () => {
    newGame({ redefineIcons: !keepIcons })
  }

  return (
    <>
      <section className='turns'>
        <Square
          isSelected={gameState.turn === 'x'}
        >
          {customIcons.x}
        </Square>
        <Square
          isSelected={gameState.turn === 'o'}
        >
          {customIcons.o}
        </Square>
      </section>
      <section className='new-game'>
        <HoldButton onClick={handleNewGame} time={200}>
          Nuevo juego
        </HoldButton>
        <label>
          Mantener íconos
          <input
            type='checkbox'
            value={keepIcons}
            onChange={() => setKeepIcons(prev => !prev)}
          />
        </label>
      </section>
    </>
  )
}
